[build]
builder = "nixpacks"
buildCommand = "npm run build --workspace=@spinout/api"

[deploy]
startCommand = "node dist/src/main"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
